#!/usr/bin/env node

var program = require('commander');
var poshutils = require('./utils');

// Task to list defaults
program
    .command('defaults')
    .description('list defaults that can be overriden by a .posh file')
    .action(function(env, options){
        console.log(JSON.stringify(poshutils.defaultConfig, null, 2));
    });

// Task to install the environment
program
    .command('install [env]')
    .description('install posh dependencies in this project')
    .action(function(env, options){
        var cfg = poshutils.loadConfig();
        downloadatomshell({
            version: cfg["atomshell-version"],
            outputDir: cfg["atomshell-directory"]
        }, function() {
            console.log("Downloaded Atom-Shell");
        });
    });

// Components task
program
    .command('comp [env]')
    .description('Work with components: Run or list')
    .option("-p, --prefixed [mode]", "Restrict listing components to these prefixes")
    .option("-d, --debug [mode]", "Enable Debug Mode at start (developer tools)")
    .option("-h, --html [mode]", "HTML start page")
    .action(function(env, options){
        switch (env) {
            case "list": poshutils.listComponents(options); break;
            default: poshutils.runComponent(env, options); break;
        }
    });

program.parse(process.argv);