#!/usr/bin/env node

var program = require('commander');
var poshutils = require('./utils');

// Task to list defaults
program
    .command('defaults')
    .description('list defaults that can be overriden by a .posh file')
    .action(function(env, options){
        console.log(JSON.stringify(poshutils.defaultConfig, null, 2));
    });

// Task to install the environment
program
    .command('create [env]')
    .description('install posh and friends for this project')
    .action(function(env, options){
        var cfg = poshutils.loadConfig();
        poshutils.create(env, cfg)
    });

// Task to install atom shell
program
    .command('installatom [env]')
    .description('install Atom-Shell (or reinstall a specific version')
    .action(function(env, options){
        var cfg = poshutils.loadConfig();
        poshutils.installatom(env, cfg)
    });

// Components task
program
    .command('comp [env]')
    .description('Work with components: Run or list')
    .option("-p, --prefixed [mode]", "Restrict listing components to these prefixes")
    .option("-d, --debug [mode]", "Enable Debug Mode at start (developer tools)")
    .action(function(env, options){
        switch (env) {
            case "list": poshutils.listComponents(options); break;
            default: poshutils.runComponent(env, options);
        }
    });

program.parse(process.argv);